/**
 * Audit log foundation. `action` / `entityType` are free-form strings so future
 * modules can add their own without touching this file; the Phase 2 catalogue
 * below documents what identity/authorization emits.
 */

export const AuditAction = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_AVATAR_UPDATED: 'USER_AVATAR_UPDATED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',
  PERMISSION_ASSIGNED: 'PERMISSION_ASSIGNED',
  PERMISSION_REMOVED: 'PERMISSION_REMOVED',
  VETERINARIAN_APPLICATION_CREATED: 'VETERINARIAN_APPLICATION_CREATED',
  VETERINARIAN_APPROVED: 'VETERINARIAN_APPROVED',
  VETERINARIAN_REJECTED: 'VETERINARIAN_REJECTED',
  SUPERVISOR_ASSIGNED: 'SUPERVISOR_ASSIGNED',
  SUPERVISOR_REMOVED: 'SUPERVISOR_REMOVED',
  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',
  SESSIONS_REVOKED: 'SESSIONS_REVOKED',

  // --- Organizations (Phase 3) ---
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  ORGANIZATION_APPROVED: 'ORGANIZATION_APPROVED',
  ORGANIZATION_REJECTED: 'ORGANIZATION_REJECTED',
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  ORGANIZATION_ACTIVATED: 'ORGANIZATION_ACTIVATED',
  ORGANIZATION_DEACTIVATED: 'ORGANIZATION_DEACTIVATED',
  ORGANIZATION_LOGO_UPDATED: 'ORGANIZATION_LOGO_UPDATED',
  ORGANIZATION_GALLERY_UPDATED: 'ORGANIZATION_GALLERY_UPDATED',
  ORGANIZATION_MEMBER_ADDED: 'ORGANIZATION_MEMBER_ADDED',
  ORGANIZATION_MEMBER_UPDATED: 'ORGANIZATION_MEMBER_UPDATED',
  ORGANIZATION_MEMBER_REMOVED: 'ORGANIZATION_MEMBER_REMOVED',
  ORGANIZATION_SUPERVISOR_ASSIGNED: 'ORGANIZATION_SUPERVISOR_ASSIGNED',
  ORGANIZATION_SUPERVISOR_UPDATED: 'ORGANIZATION_SUPERVISOR_UPDATED',
  ORGANIZATION_SUPERVISOR_REMOVED: 'ORGANIZATION_SUPERVISOR_REMOVED',

  // --- Animals & ownership (Phase 4) ---
  ANIMAL_CREATED: 'ANIMAL_CREATED',
  ANIMAL_UPDATED: 'ANIMAL_UPDATED',
  ANIMAL_DEACTIVATED: 'ANIMAL_DEACTIVATED',
  ANIMAL_GALLERY_UPDATED: 'ANIMAL_GALLERY_UPDATED',
  ANIMAL_OWNERSHIP_TRANSFERRED: 'ANIMAL_OWNERSHIP_TRANSFERRED',

  // --- Veterinary care (Phase 5) ---
  ANIMAL_CLINIC_ACCESS_GRANTED: 'ANIMAL_CLINIC_ACCESS_GRANTED',
  ANIMAL_CLINIC_ACCESS_REVOKED: 'ANIMAL_CLINIC_ACCESS_REVOKED',
  MEDICAL_RECORD_CREATED: 'MEDICAL_RECORD_CREATED',
  MEDICAL_RECORD_UPDATED: 'MEDICAL_RECORD_UPDATED',
  MEDICAL_RECORD_DELETED: 'MEDICAL_RECORD_DELETED',
  VACCINATION_CREATED: 'VACCINATION_CREATED',
  VACCINATION_UPDATED: 'VACCINATION_UPDATED',
  VACCINATION_DELETED: 'VACCINATION_DELETED',

  // --- Farms & poultry (Phase 6) ---
  FARM_MEMBER_JOINED: 'FARM_MEMBER_JOINED',
  FARM_JOIN_CODE_REGENERATED: 'FARM_JOIN_CODE_REGENERATED',
  POULTRY_FLOCK_CREATED: 'POULTRY_FLOCK_CREATED',
  POULTRY_FLOCK_UPDATED: 'POULTRY_FLOCK_UPDATED',
  POULTRY_FLOCK_DELETED: 'POULTRY_FLOCK_DELETED',

  // --- Animal publications: Lost / Adoption / Mating (Phase 7) ---
  LOST_ANIMAL_CREATED: 'LOST_ANIMAL_CREATED',
  LOST_ANIMAL_APPROVED: 'LOST_ANIMAL_APPROVED',
  LOST_ANIMAL_REJECTED: 'LOST_ANIMAL_REJECTED',
  ADOPTION_CREATED: 'ADOPTION_CREATED',
  ADOPTION_APPROVED: 'ADOPTION_APPROVED',
  ADOPTION_REJECTED: 'ADOPTION_REJECTED',
  MATING_CREATED: 'MATING_CREATED',
  MATING_APPROVED: 'MATING_APPROVED',
  MATING_REJECTED: 'MATING_REJECTED',

  // --- Veterinary store & products (Phase 10) ---
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  PRODUCT_INVENTORY_ADJUSTED: 'PRODUCT_INVENTORY_ADJUSTED',

  // --- Chat & messaging (Phase 12) ---
  // Normal text messages are NOT audited (docs §39); only state-changing
  // conversation/message management is.
  CONVERSATION_CREATED: 'CONVERSATION_CREATED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',

  // --- Consultations & inquiries (Phase 13) ---
  // Normal thread messages are NOT audited; only lifecycle transitions are.
  CONSULTATION_CREATED: 'CONSULTATION_CREATED',
  CONSULTATION_CLOSED: 'CONSULTATION_CLOSED',
  CONSULTATION_SENDER_BLOCKED: 'CONSULTATION_SENDER_BLOCKED',
  CONSULTATION_SENDER_UNBLOCKED: 'CONSULTATION_SENDER_UNBLOCKED',
  INQUIRY_CREATED: 'INQUIRY_CREATED',
  INQUIRY_CLOSED: 'INQUIRY_CLOSED',
  INQUIRY_SENDER_BLOCKED: 'INQUIRY_SENDER_BLOCKED',
  INQUIRY_SENDER_UNBLOCKED: 'INQUIRY_SENDER_UNBLOCKED',
  AI_SETTING_UPDATED: 'AI_SETTING_UPDATED',

  // --- Content management (Phase 14) ---
  CONTENT_CREATED: 'CONTENT_CREATED',
  CONTENT_UPDATED: 'CONTENT_UPDATED',
  CONTENT_PUBLISHED: 'CONTENT_PUBLISHED',
  CONTENT_ARCHIVED: 'CONTENT_ARCHIVED',
  CONTENT_DELETED: 'CONTENT_DELETED',
  CONTENT_RESTORED: 'CONTENT_RESTORED',
  CONTENT_FILE_UPLOADED: 'CONTENT_FILE_UPLOADED',
  CONTENT_FILE_REPLACED: 'CONTENT_FILE_REPLACED',
  CONTENT_FILE_DELETED: 'CONTENT_FILE_DELETED',
  CONTENT_CATEGORY_CREATED: 'CONTENT_CATEGORY_CREATED',
  CONTENT_CATEGORY_UPDATED: 'CONTENT_CATEGORY_UPDATED',
  CONTENT_CATEGORY_DELETED: 'CONTENT_CATEGORY_DELETED',

  // --- Tips (structured care advice inside the content module) ---
  TIP_CREATED: 'TIP_CREATED',
  TIP_UPDATED: 'TIP_UPDATED',
  TIP_PUBLISHED: 'TIP_PUBLISHED',
  TIP_ARCHIVED: 'TIP_ARCHIVED',
  TIP_DELETED: 'TIP_DELETED',
  TIP_RESTORED: 'TIP_RESTORED',
  TIP_COVER_UPDATED: 'TIP_COVER_UPDATED',
  TIP_OF_DAY_SET: 'TIP_OF_DAY_SET',
  TIP_OF_DAY_CLEARED: 'TIP_OF_DAY_CLEARED',

  // --- Notifications & FCM (Phase 15) ---
  // Normal notification creation / read is NOT audited — only device-token and
  // administrative actions.
  DEVICE_TOKEN_REGISTERED: 'DEVICE_TOKEN_REGISTERED',
  DEVICE_TOKEN_REVOKED: 'DEVICE_TOKEN_REVOKED',
  ADMIN_NOTIFICATION_SENT: 'ADMIN_NOTIFICATION_SENT',
  NOTIFICATION_PREFERENCE_UPDATED: 'NOTIFICATION_PREFERENCE_UPDATED',

  // --- Advertisements (multi-section campaigns + ordered slides) ---
  AD_CAMPAIGN_CREATED: 'AD_CAMPAIGN_CREATED',
  AD_CAMPAIGN_UPDATED: 'AD_CAMPAIGN_UPDATED',
  AD_CAMPAIGN_ACTIVATED: 'AD_CAMPAIGN_ACTIVATED',
  AD_CAMPAIGN_DEACTIVATED: 'AD_CAMPAIGN_DEACTIVATED',
  AD_CAMPAIGN_DELETED: 'AD_CAMPAIGN_DELETED',
  AD_CAMPAIGN_RESTORED: 'AD_CAMPAIGN_RESTORED',
  AD_SLIDE_ADDED: 'AD_SLIDE_ADDED',
  AD_SLIDE_UPDATED: 'AD_SLIDE_UPDATED',
  AD_SLIDE_REMOVED: 'AD_SLIDE_REMOVED',
  AD_SLIDE_REORDERED: 'AD_SLIDE_REORDERED',
  AD_SLIDE_IMAGE_UPDATED: 'AD_SLIDE_IMAGE_UPDATED',
} as const;
export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  USER: 'USER',
  ROLE: 'ROLE',
  PERMISSION: 'PERMISSION',
  USER_ROLE: 'USER_ROLE',
  ROLE_PERMISSION: 'ROLE_PERMISSION',
  VETERINARIAN_APPLICATION: 'VETERINARIAN_APPLICATION',
  SYSTEM_SUPERVISOR_ASSIGNMENT: 'SYSTEM_SUPERVISOR_ASSIGNMENT',
  REFRESH_SESSION: 'REFRESH_SESSION',
  ORGANIZATION: 'ORGANIZATION',
  ORGANIZATION_MEMBERSHIP: 'ORGANIZATION_MEMBERSHIP',
  ANIMAL: 'ANIMAL',
  ANIMAL_OWNERSHIP: 'ANIMAL_OWNERSHIP',
  ANIMAL_CLINIC_ACCESS: 'ANIMAL_CLINIC_ACCESS',
  MEDICAL_RECORD: 'MEDICAL_RECORD',
  VACCINATION: 'VACCINATION',
  POULTRY_FLOCK: 'POULTRY_FLOCK',
  ANIMAL_PUBLICATION: 'ANIMAL_PUBLICATION',
  PRODUCT: 'PRODUCT',
  CONVERSATION: 'CONVERSATION',
  MESSAGE: 'MESSAGE',
  CONSULTATION: 'CONSULTATION',
  INQUIRY: 'INQUIRY',
  AI_SETTING: 'AI_SETTING',
  CONTENT: 'CONTENT',
  CONTENT_FILE: 'CONTENT_FILE',
  CONTENT_CATEGORY: 'CONTENT_CATEGORY',
  TIP: 'TIP',
  NOTIFICATION: 'NOTIFICATION',
  DEVICE_PUSH_TOKEN: 'DEVICE_PUSH_TOKEN',
  AD_CAMPAIGN: 'AD_CAMPAIGN',
  AD_SLIDE: 'AD_SLIDE',
} as const;
export type AuditEntityTypeValue = (typeof AuditEntityType)[keyof typeof AuditEntityType];

/** Request-derived context. Never contains credentials. */
export interface AuditContext {
  ip?: string | null;
  userAgent?: string | null;
  requestId?: string | null;
}

export interface AuditEntryInput {
  action: string;
  entityType: string;
  entityId?: string | null;
  actorUserId?: string | null;
  metadata?: Record<string, unknown>;
  context?: AuditContext;
}

export interface AuditLogRecord {
  id: string;
  actorUserId: string | null;
  action: string;
  entityType: string;
  entityId: string | null;
  metadata: Record<string, unknown>;
  ip: string | null;
  userAgent: string | null;
  requestId: string | null;
  createdAt: string;
}

export interface ListAuditFilter {
  page: number;
  pageSize: number;
  action?: string;
  entityType?: string;
  entityId?: string;
  actorUserId?: string;
  from?: Date;
  to?: Date;
}

export interface AuditLogRow {
  id: string;
  actor_user_id: string | null;
  action: string;
  entity_type: string;
  entity_id: string | null;
  metadata: Record<string, unknown>;
  ip: string | null;
  user_agent: string | null;
  request_id: string | null;
  created_at: Date;
}
