import type { Knex } from 'knex';
import type { Logger } from 'pino';
import {
  BadRequestError,
  ConflictError,
  InternalError,
  NotFoundError,
} from '../../../shared/errors/app-error.js';
import { ErrorCode } from '../../../shared/errors/error-codes.js';
import type { EventBus } from '../../../shared/events/index.js';
import { buildObjectKey, StoragePrefix, type ObjectStorage } from '../../../infra/storage/index.js';
import { AuditAction, AuditEntityType, type AuditContext } from '../../audit/audit.types.js';
import type { AuditService } from '../../audit/audit.service.js';
import type { UserService } from '../../users/user.service.js';
import { OrganizationPolicy } from '../domain/organization.policy.js';
import { OWNER_ORG_ROLE_KEY } from '../domain/organization-rbac.constants.js';
import {
  computeFarmSubscriptionStatus,
  toPublicOrganizationDTO,
  type FarmSubscriptionStatus,
  type Organization,
  type OrganizationStatus,
  type OrganizationType,
  type OrganizationWithDetails,
  type PublicOrganizationDTO,
} from '../domain/organization.types.js';
import type { MembershipRepository } from '../infrastructure/membership.repository.js';
import type { OrganizationRbacRepository } from '../infrastructure/organization-rbac.repository.js';
import type {
  ListOrganizationsFilter,
  OrganizationRepository,
} from '../infrastructure/organization.repository.js';

function toDateOnlyString(v: string | Date | null): string | null {
  if (v === null) return null;
  return v instanceof Date ? v.toISOString().slice(0, 10) : v.slice(0, 10);
}

/** Shared by the logo AND the gallery — both are plain organization photos. */
const ALLOWED_IMAGE_MIME = ['image/png', 'image/jpeg', 'image/webp'] as const;
/** Hard ceiling per image (5 MiB — mirrors the user avatar limit). */
const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
const IMAGE_UPLOAD_URL_TTL_SECONDS = 600;
const IMAGE_URL_TTL_SECONDS = 3600;
/** Directory profile photos beyond the logo — the Clinic Details carousel. */
const MAX_GALLERY_IMAGES = 8;
/** License/registration document photos — "صور الترخيص" on the registration form. */
const MAX_LICENSE_DOCUMENTS = 3;
/** CLINIC / VETERINARY_OFFICE only — narrower than `hasProfileFields` (excludes VETERINARY_STORE). */
const LICENSABLE_TYPES: ReadonlySet<OrganizationType> = new Set(['CLINIC', 'VETERINARY_OFFICE']);

export interface OrgActor {
  actorUserId: string;
  context?: AuditContext;
}

/**
 * Type-specific detail columns written into the subtype `*_details` row in the
 * SAME transaction as the organization + owner membership. Keys are the exact
 * DB column names of that detail table (e.g. `farm_details`); a domain-specific
 * creation use case (the "Add Poultry Farm" form) builds this map. Unknown
 * columns are a DB error, never a silent drop. `join_code` for FARM is still
 * generated by the service and merged on top.
 */
export type CreateOrganizationDetails = Record<string, string | number | boolean | string[] | null>;

/**
 * Typed, camelCase profile fields for `hasProfileFields` types (CLINIC /
 * VETERINARY_OFFICE / VETERINARY_STORE) — separate from the raw-snake-case
 * `details` escape hatch above (used by FARM/livestock creation, whose fields
 * live on a differently-shaped table). The "تسجيل العيادة" / office
 * registration screens capture the full profile in one submission instead of
 * create-then-PATCH, because the owner cannot call `PATCH` (or the
 * gallery/license-document endpoints without `allowInactiveForOwner`) until
 * an admin approves the PENDING organization.
 */
export interface CreateOrganizationProfileInput {
  address?: string | null;
  country?: string | null;
  phone?: string | null;
  workingHours?: string | null;
  services?: string[];
  email?: string | null;
  whatsapp?: string | null;
  websiteUrl?: string | null;
  instagramUrl?: string | null;
  facebookUrl?: string | null;
  tiktokUrl?: string | null;
  /** CLINIC / VETERINARY_OFFICE only. */
  licenseNumber?: string | null;
}

export interface CreateOrganizationInput {
  type: OrganizationType;
  name: string;
  description?: string | null;
  /** Raw snake-case detail columns — FARM/livestock creation. */
  details?: CreateOrganizationDetails;
  /** Typed camelCase profile fields — CLINIC / VETERINARY_OFFICE / VETERINARY_STORE registration. */
  profile?: CreateOrganizationProfileInput;
}

const NON_ADMIN_STATUS_CHANGE: Record<
  'suspend' | 'activate' | 'deactivate',
  { to: OrganizationStatus; from: OrganizationStatus[]; action: string; event: string }
> = {
  suspend: {
    to: 'SUSPENDED',
    from: ['ACTIVE', 'SUSPENDED'],
    action: AuditAction.ORGANIZATION_SUSPENDED,
    event: 'organization.suspended',
  },
  activate: {
    to: 'ACTIVE',
    from: ['SUSPENDED', 'DEACTIVATED', 'ACTIVE'],
    action: AuditAction.ORGANIZATION_ACTIVATED,
    event: 'organization.activated',
  },
  deactivate: {
    to: 'DEACTIVATED',
    from: ['ACTIVE', 'SUSPENDED', 'DEACTIVATED'],
    action: AuditAction.ORGANIZATION_DEACTIVATED,
    event: 'organization.deactivated',
  },
};

/**
 * Common organization lifecycle: creation (→ PENDING), admin approval/rejection,
 * admin status changes, and reads. Type-specific rules live in
 * {@link OrganizationPolicy} — never inlined here.
 */
export class OrganizationService {
  private readonly log: Logger;

  constructor(
    private readonly db: Knex,
    private readonly organizations: OrganizationRepository,
    private readonly memberships: MembershipRepository,
    private readonly orgRbac: OrganizationRbacRepository,
    private readonly users: UserService,
    private readonly audit: AuditService,
    private readonly events: EventBus,
    private readonly storage: ObjectStorage,
    logger: Logger,
  ) {
    this.log = logger.child({ component: 'organization-service' });
  }

  /**
   * Resolve one stored image key to a client-usable URL (public CDN URL when
   * the bucket is public, else a short-lived signed GET). Public so admin
   * presentation code can resolve keys that come straight off a repository
   * projection (e.g. the admin farm list) without its own storage handle.
   */
  resolveImageUrl(key: string | null): Promise<string | null> {
    return this.resolveLogoUrl(key);
  }

  private async resolveLogoUrl(key: string | null): Promise<string | null> {
    if (!key) return null;
    return (
      this.storage.getPublicUrl(key) ??
      (await this.storage.getSignedUrl(key, { operation: 'get', expiresIn: IMAGE_URL_TTL_SECONDS }))
    );
  }

  private async resolveGalleryUrls(keys: string[]): Promise<string[]> {
    if (keys.length === 0) return [];
    const urls = await Promise.all(keys.map((key) => this.resolveLogoUrl(key)));
    return urls.filter((u): u is string => u !== null);
  }

  /**
   * `findByIdWithDetails` fills address/coordinates/phone but deliberately
   * leaves `logoUrl` / `galleryUrls` unset — resolving storage keys to URLs is
   * an application concern, not the repository's. This attaches them (a
   * second, cheap profile-row read; detail reads aren't a hot path).
   */
  private async attachMedia(
    withDetails: OrganizationWithDetails,
  ): Promise<OrganizationWithDetails> {
    if (withDetails.type === 'FARM') {
      // FARM has no directory profile — its single photo lives on `farm_details`.
      const imageKey = await this.organizations.findFarmImageKey(withDetails.id);
      return {
        ...withDetails,
        details: { ...withDetails.details, imageUrl: await this.resolveLogoUrl(imageKey) },
      };
    }
    if (!OrganizationPolicy.hasProfileFields(withDetails.type)) return withDetails;
    const row = await this.organizations.findProfileRow(withDetails.type, withDetails.id);
    const galleryKeys = row?.gallery_keys ?? [];
    const licenseDocumentKeys = row?.license_document_keys ?? [];
    const [logoUrl, galleryUrls, licenseDocumentUrls] = await Promise.all([
      this.resolveLogoUrl(row?.logo_key ?? null),
      this.resolveGalleryUrls(galleryKeys),
      this.resolveGalleryUrls(licenseDocumentKeys),
    ]);
    const extra =
      withDetails.type === 'VETERINARY_OFFICE' || withDetails.type === 'CLINIC'
        ? { licenseDocumentUrls, licenseDocumentKeys }
        : {};
    return {
      ...withDetails,
      details: { ...withDetails.details, logoUrl, galleryUrls, galleryKeys, ...extra },
    };
  }

  async create(input: CreateOrganizationInput, actor: OrgActor): Promise<OrganizationWithDetails> {
    const creator = await this.users.getById(actor.actorUserId);
    OrganizationPolicy.assertCanCreate(input.type, creator);
    OrganizationPolicy.validateTypeSpecificRules(input.type, input);

    const org = await this.db.transaction(async (tx) => {
      const ownerRole = await this.orgRbac.findRoleByKey(OWNER_ORG_ROLE_KEY, tx);
      if (!ownerRole) throw new InternalError('Seed data missing: organization role "OWNER"');

      const created = await this.organizations.create(
        {
          type: input.type,
          name: input.name,
          description: input.description ?? null,
          ownerUserId: actor.actorUserId,
        },
        tx,
      );

      const detailExtra: Record<string, unknown> = { ...(input.details ?? {}) };
      if (input.profile && OrganizationPolicy.hasProfileFields(input.type)) {
        const p = input.profile;
        if (p.address !== undefined) detailExtra.address = p.address;
        if (p.country !== undefined) detailExtra.country = p.country;
        if (p.phone !== undefined) detailExtra.phone = p.phone;
        if (p.workingHours !== undefined) detailExtra.working_hours = p.workingHours;
        if (p.services !== undefined) detailExtra.services = p.services;
        if (p.email !== undefined) detailExtra.email = p.email;
        if (p.whatsapp !== undefined) detailExtra.whatsapp = p.whatsapp;
        if (p.websiteUrl !== undefined) detailExtra.website_url = p.websiteUrl;
        if (p.instagramUrl !== undefined) detailExtra.instagram_url = p.instagramUrl;
        if (p.facebookUrl !== undefined) detailExtra.facebook_url = p.facebookUrl;
        if (p.tiktokUrl !== undefined) detailExtra.tiktok_url = p.tiktokUrl;
        if (p.licenseNumber !== undefined && LICENSABLE_TYPES.has(input.type)) {
          detailExtra.license_number = p.licenseNumber;
        }
      }
      if (OrganizationPolicy.hasJoinCode(input.type)) {
        detailExtra.join_code = OrganizationPolicy.generateJoinCode();
      }
      await this.organizations.insertDetails(input.type, created.id, detailExtra, tx);

      const membership = await this.memberships.create(
        {
          organizationId: created.id,
          userId: actor.actorUserId,
          organizationRoleId: ownerRole.id,
          status: 'ACTIVE',
          addedBy: actor.actorUserId,
        },
        tx,
      );

      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_CREATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: created.id,
          actorUserId: actor.actorUserId,
          metadata: { type: created.type, name: created.name },
          context: actor.context,
        },
        tx,
      );
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_MEMBER_ADDED,
          entityType: AuditEntityType.ORGANIZATION_MEMBERSHIP,
          entityId: membership.id,
          actorUserId: actor.actorUserId,
          metadata: { organizationId: created.id, userId: actor.actorUserId, roleKey: 'OWNER' },
          context: actor.context,
        },
        tx,
      );
      return created;
    });

    this.events.publish('organization.created', {
      organizationId: org.id,
      type: org.type,
      ownerUserId: org.ownerUserId,
    });

    const withDetails = await this.organizations.findByIdWithDetails(org.id);
    if (!withDetails) throw new InternalError('organization vanished after creation');
    return this.attachMedia(withDetails);
  }

  async getWithDetails(id: string): Promise<OrganizationWithDetails | null> {
    const withDetails = await this.organizations.findByIdWithDetails(id);
    return withDetails ? this.attachMedia(withDetails) : null;
  }

  async updateProfile(
    id: string,
    patch: {
      name?: string;
      description?: string | null;
      address?: string | null;
      country?: string | null;
      phone?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      workingHours?: string | null;
      services?: string[] | null;
      email?: string | null;
      whatsapp?: string | null;
      websiteUrl?: string | null;
      instagramUrl?: string | null;
      facebookUrl?: string | null;
      tiktokUrl?: string | null;
      /** CLINIC / VETERINARY_OFFICE only. */
      licenseNumber?: string | null;
    },
    actor: OrgActor,
  ): Promise<OrganizationWithDetails> {
    const profileFieldKeys = (
      [
        'address',
        'country',
        'phone',
        'latitude',
        'longitude',
        'workingHours',
        'services',
        'email',
        'whatsapp',
        'websiteUrl',
        'instagramUrl',
        'facebookUrl',
        'tiktokUrl',
      ] as const
    ).filter((k) => patch[k] !== undefined);
    const org = await this.getById(id);
    if (profileFieldKeys.length > 0) OrganizationPolicy.assertHasProfileFields(org.type);
    if (patch.licenseNumber !== undefined) this.assertLicensable(org.type);

    await this.db.transaction(async (tx) => {
      await this.organizations.update(id, { name: patch.name, description: patch.description }, tx);
      if (profileFieldKeys.length > 0 || patch.licenseNumber !== undefined) {
        await this.organizations.updateProfileFields(
          org.type,
          id,
          {
            address: patch.address,
            country: patch.country,
            phone: patch.phone,
            latitude: patch.latitude,
            longitude: patch.longitude,
            workingHours: patch.workingHours,
            services: patch.services,
            email: patch.email,
            whatsapp: patch.whatsapp,
            websiteUrl: patch.websiteUrl,
            instagramUrl: patch.instagramUrl,
            facebookUrl: patch.facebookUrl,
            tiktokUrl: patch.tiktokUrl,
            licenseNumber: patch.licenseNumber,
          },
          tx,
        );
      }
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_UPDATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: id,
          actorUserId: actor.actorUserId,
          metadata: { fields: Object.keys(patch) },
          context: actor.context,
        },
        tx,
      );
    });
    const withDetails = await this.organizations.findByIdWithDetails(id);
    if (!withDetails) throw new InternalError('organization vanished after update');
    return this.attachMedia(withDetails);
  }

  async getById(id: string): Promise<Organization> {
    const org = await this.organizations.findById(id);
    if (!org) throw new NotFoundError('Organization not found');
    return org;
  }

  async listForAdmin(
    filter: ListOrganizationsFilter,
  ): Promise<{ items: Array<Organization & { logoUrl?: string | null }>; total: number }> {
    const { items, total } = await this.organizations.list(filter);
    return { items: await this.attachLogoUrls(items), total };
  }

  async listPendingForAdmin(
    page: number,
    pageSize: number,
  ): Promise<{ items: Array<Organization & { logoUrl?: string | null }>; total: number }> {
    const { items, total } = await this.organizations.list({ page, pageSize, status: 'PENDING' });
    return { items: await this.attachLogoUrls(items), total };
  }

  /**
   * Batched `logoUrl` resolution for an admin LIST page (bounded by
   * `pageSize`, never the whole table) — mirrors `listMine`'s pattern so the
   * "المكاتب"/"العيادات" admin screens can show a thumbnail per row without
   * an N+1 query per organization.
   */
  private async attachLogoUrls<T extends Organization>(
    items: T[],
  ): Promise<Array<T & { logoUrl: string | null }>> {
    const detailsTableByType: Partial<Record<OrganizationType, string>> = {
      CLINIC: 'clinic_details',
      VETERINARY_OFFICE: 'veterinary_office_details',
      VETERINARY_STORE: 'veterinary_store_details',
    };
    const byType = new Map<OrganizationType, string[]>();
    for (const item of items) {
      if (!detailsTableByType[item.type]) continue;
      const ids = byType.get(item.type) ?? [];
      ids.push(item.id);
      byType.set(item.type, ids);
    }
    if (byType.size === 0) return items.map((item) => ({ ...item, logoUrl: null }));

    const logoKeyByOrg = new Map<string, string | null>();
    await Promise.all(
      [...byType.entries()].map(async ([type, ids]) => {
        const table = detailsTableByType[type] as string;
        const rows = (await this.db(table)
          .whereIn('organization_id', ids)
          .select('organization_id', 'logo_key')) as Array<{
          organization_id: string;
          logo_key: string | null;
        }>;
        for (const r of rows) logoKeyByOrg.set(r.organization_id, r.logo_key);
      }),
    );

    const urlByKey = new Map<string, string | null>();
    await Promise.all(
      [...logoKeyByOrg.values()]
        .filter((key): key is string => key !== null)
        .map(async (key) => {
          if (!urlByKey.has(key)) urlByKey.set(key, await this.resolveLogoUrl(key));
        }),
    );

    return items.map((item) => {
      const logoKey = logoKeyByOrg.get(item.id) ?? null;
      return { ...item, logoUrl: logoKey ? (urlByKey.get(logoKey) ?? null) : null };
    });
  }

  /**
   * Public discovery — any authenticated user, not just members (e.g. the Pet
   * Owner Home "Available clinics" section / `DiscoverClinicsScreen`). ACTIVE
   * organizations only; the narrower {@link PublicOrganizationDTO} omits
   * owner/decision metadata.
   *
   * When `type` has a directory profile (CLINIC / VETERINARY_OFFICE /
   * VETERINARY_STORE), the listing is joined with that profile (address,
   * coordinates, phone, logo) and, if `near` is given, ordered by distance —
   * see `OrganizationRepository.discoverWithDetails`. Any other `type`
   * (including FARM, or no type at all) falls back to the plain listing with
   * empty profile fields; `near` is ignored there since there is nothing to
   * measure distance from.
   */
  async discoverPublic(filter: {
    page: number;
    pageSize: number;
    type?: OrganizationType;
    search?: string;
    near?: { lat: number; lng: number };
  }): Promise<{ items: PublicOrganizationDTO[]; total: number }> {
    if (filter.type && OrganizationPolicy.hasProfileFields(filter.type)) {
      const { items, total } = await this.organizations.discoverWithDetails({
        type: filter.type,
        search: filter.search,
        near: filter.near,
        page: filter.page,
        pageSize: filter.pageSize,
      });
      const dtos = await Promise.all(
        items.map(async (item) => {
          const { logoKey, ...profile } = item.profile;
          const logoUrl = await this.resolveLogoUrl(logoKey);
          return toPublicOrganizationDTO(
            item.organization,
            { ...profile, logoUrl },
            item.distanceKm,
          );
        }),
      );
      return { items: dtos, total };
    }

    const { items, total } = await this.organizations.list({
      page: filter.page,
      pageSize: filter.pageSize,
      type: filter.type,
      search: filter.search,
      status: 'ACTIVE',
    });
    return { items: items.map((org) => toPublicOrganizationDTO(org)), total };
  }

  /** Single-organization counterpart of {@link discoverPublic} — ACTIVE only. */
  async getPublicById(id: string): Promise<PublicOrganizationDTO> {
    const org = await this.organizations.findById(id);
    if (!org || org.status !== 'ACTIVE') throw new NotFoundError('Organization not found');
    if (!OrganizationPolicy.hasProfileFields(org.type)) return toPublicOrganizationDTO(org);

    const row = await this.organizations.findProfileRow(org.type, id);
    const [logoUrl, galleryUrls] = await Promise.all([
      this.resolveLogoUrl(row?.logo_key ?? null),
      this.resolveGalleryUrls(row?.gallery_keys ?? []),
    ]);
    return toPublicOrganizationDTO(org, {
      address: row?.address ?? null,
      country: row?.country ?? null,
      latitude: row?.latitude ?? null,
      longitude: row?.longitude ?? null,
      phone: row?.phone ?? null,
      logoUrl,
      workingHours: row?.working_hours ?? null,
      services: row?.services ?? [],
      email: row?.email ?? null,
      whatsapp: row?.whatsapp ?? null,
      websiteUrl: row?.website_url ?? null,
      instagramUrl: row?.instagram_url ?? null,
      facebookUrl: row?.facebook_url ?? null,
      tiktokUrl: row?.tiktok_url ?? null,
      galleryUrls,
    });
  }

  // --- logo (presigned direct-to-storage upload) --------------------

  async requestLogoUploadUrl(
    organizationId: string,
    input: { filename: string; mimeType: string; size: number },
  ): Promise<{
    storageKey: string;
    uploadUrl: string;
    method: 'PUT';
    headers: Record<string, string>;
    expiresInSeconds: number;
  }> {
    const org = await this.getById(organizationId);
    OrganizationPolicy.assertHasProfileFields(org.type);

    if (!Number.isInteger(input.size) || input.size <= 0) {
      throw new BadRequestError('size must be a positive integer number of bytes');
    }
    if (input.size > MAX_IMAGE_BYTES) {
      throw new BadRequestError(`logo exceeds the ${MAX_IMAGE_BYTES}-byte limit`, {
        code: ErrorCode.FILE_TOO_LARGE,
      });
    }
    if (!ALLOWED_IMAGE_MIME.includes(input.mimeType as (typeof ALLOWED_IMAGE_MIME)[number])) {
      throw new BadRequestError(`MIME type "${input.mimeType}" is not allowed for a logo`, {
        code: ErrorCode.UNSUPPORTED_FILE_TYPE,
      });
    }

    // The server ALWAYS generates the key — the client never controls it.
    const storageKey = buildObjectKey(StoragePrefix.organizationFiles, input.filename);
    const uploadUrl = await this.storage.getSignedUrl(storageKey, {
      operation: 'put',
      expiresIn: IMAGE_UPLOAD_URL_TTL_SECONDS,
      contentType: input.mimeType,
    });

    return {
      storageKey,
      uploadUrl,
      method: 'PUT',
      headers: { 'Content-Type': input.mimeType },
      expiresInSeconds: IMAGE_UPLOAD_URL_TTL_SECONDS,
    };
  }

  async finalizeLogo(
    organizationId: string,
    actor: OrgActor,
    input: { storageKey: string; mimeType: string },
  ): Promise<OrganizationWithDetails> {
    const org = await this.getById(organizationId);
    OrganizationPolicy.assertHasProfileFields(org.type);
    if (!input.storageKey.startsWith(`${StoragePrefix.organizationFiles}/`)) {
      throw new ConflictError('storage key does not belong to organization uploads', {
        code: ErrorCode.STORAGE_KEY_MISMATCH,
      });
    }

    const head = await this.storage.head(input.storageKey);
    if (!head) {
      throw new BadRequestError('no uploaded object exists at that storage key', {
        code: ErrorCode.STORAGE_OBJECT_MISSING,
      });
    }
    const realMime = head.contentType ?? input.mimeType;
    if (head.size > MAX_IMAGE_BYTES) {
      throw new BadRequestError('the uploaded object exceeds the size limit', {
        code: ErrorCode.FILE_TOO_LARGE,
      });
    }
    if (!ALLOWED_IMAGE_MIME.includes(realMime as (typeof ALLOWED_IMAGE_MIME)[number])) {
      throw new BadRequestError(`the uploaded object's type "${realMime}" is not allowed`, {
        code: ErrorCode.UNSUPPORTED_FILE_TYPE,
      });
    }

    const previousRow = await this.organizations.findProfileRow(org.type, organizationId);
    const previousKey = previousRow?.logo_key ?? null;

    await this.db.transaction(async (tx) => {
      await this.organizations.updateProfileFields(
        org.type,
        organizationId,
        { logoKey: input.storageKey },
        tx,
      );
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_LOGO_UPDATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: organizationId,
          actorUserId: actor.actorUserId,
          // NB: no storage key / URL / credentials in audit metadata.
          metadata: { organizationId, sizeBytes: head.size },
          context: actor.context,
        },
        tx,
      );
    });

    // Best-effort cleanup of the replaced object AFTER commit (§28 pattern).
    if (previousKey && previousKey !== input.storageKey) {
      try {
        await this.storage.delete(previousKey);
      } catch (err) {
        this.log.error(
          { err, organizationId },
          'failed to delete replaced organization logo — needs a sweep',
        );
      }
    }

    const withDetails = await this.organizations.findByIdWithDetails(organizationId);
    if (!withDetails) throw new InternalError('organization vanished after logo update');
    return this.attachMedia(withDetails);
  }

  /** Clears the organization's logo, if any. */
  async removeLogo(organizationId: string, actor: OrgActor): Promise<OrganizationWithDetails> {
    const org = await this.getById(organizationId);
    OrganizationPolicy.assertHasProfileFields(org.type);

    const row = await this.organizations.findProfileRow(org.type, organizationId);
    const previousKey = row?.logo_key ?? null;
    if (!previousKey) {
      throw new NotFoundError('This organization has no logo to remove');
    }

    await this.db.transaction(async (tx) => {
      await this.organizations.updateProfileFields(org.type, organizationId, { logoKey: null }, tx);
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_LOGO_UPDATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: organizationId,
          actorUserId: actor.actorUserId,
          metadata: { organizationId, removed: true },
          context: actor.context,
        },
        tx,
      );
    });

    try {
      await this.storage.delete(previousKey);
    } catch (err) {
      this.log.error({ err, organizationId }, 'failed to delete removed organization logo — needs a sweep');
    }

    const withDetails = await this.organizations.findByIdWithDetails(organizationId);
    if (!withDetails) throw new InternalError('organization vanished after logo update');
    return this.attachMedia(withDetails);
  }

  // --- gallery (presigned direct-to-storage upload, N photos) -------

  /** Same validation/URL shape as {@link requestLogoUploadUrl} — one photo at a time. */
  async requestGalleryUploadUrl(
    organizationId: string,
    input: { filename: string; mimeType: string; size: number },
  ): Promise<{
    storageKey: string;
    uploadUrl: string;
    method: 'PUT';
    headers: Record<string, string>;
    expiresInSeconds: number;
  }> {
    const org = await this.getById(organizationId);
    OrganizationPolicy.assertHasProfileFields(org.type);

    if (!Number.isInteger(input.size) || input.size <= 0) {
      throw new BadRequestError('size must be a positive integer number of bytes');
    }
    if (input.size > MAX_IMAGE_BYTES) {
      throw new BadRequestError(`photo exceeds the ${MAX_IMAGE_BYTES}-byte limit`, {
        code: ErrorCode.FILE_TOO_LARGE,
      });
    }
    if (!ALLOWED_IMAGE_MIME.includes(input.mimeType as (typeof ALLOWED_IMAGE_MIME)[number])) {
      throw new BadRequestError(`MIME type "${input.mimeType}" is not allowed for a photo`, {
        code: ErrorCode.UNSUPPORTED_FILE_TYPE,
      });
    }

    const row = await this.organizations.findProfileRow(org.type, organizationId);
    if ((row?.gallery_keys?.length ?? 0) >= MAX_GALLERY_IMAGES) {
      throw new BadRequestError(
        `the gallery already has the maximum of ${MAX_GALLERY_IMAGES} photos`,
        {
          code: ErrorCode.GALLERY_LIMIT_EXCEEDED,
        },
      );
    }

    const storageKey = buildObjectKey(StoragePrefix.organizationFiles, input.filename);
    const uploadUrl = await this.storage.getSignedUrl(storageKey, {
      operation: 'put',
      expiresIn: IMAGE_UPLOAD_URL_TTL_SECONDS,
      contentType: input.mimeType,
    });

    return {
      storageKey,
      uploadUrl,
      method: 'PUT',
      headers: { 'Content-Type': input.mimeType },
      expiresInSeconds: IMAGE_UPLOAD_URL_TTL_SECONDS,
    };
  }

  /** Registers an uploaded gallery photo — appends to the existing array. */
  async addGalleryImage(
    organizationId: string,
    actor: OrgActor,
    input: { storageKey: string; mimeType: string },
  ): Promise<OrganizationWithDetails> {
    const org = await this.getById(organizationId);
    OrganizationPolicy.assertHasProfileFields(org.type);
    if (!input.storageKey.startsWith(`${StoragePrefix.organizationFiles}/`)) {
      throw new ConflictError('storage key does not belong to organization uploads', {
        code: ErrorCode.STORAGE_KEY_MISMATCH,
      });
    }

    const head = await this.storage.head(input.storageKey);
    if (!head) {
      throw new BadRequestError('no uploaded object exists at that storage key', {
        code: ErrorCode.STORAGE_OBJECT_MISSING,
      });
    }
    const realMime = head.contentType ?? input.mimeType;
    if (head.size > MAX_IMAGE_BYTES) {
      throw new BadRequestError('the uploaded object exceeds the size limit', {
        code: ErrorCode.FILE_TOO_LARGE,
      });
    }
    if (!ALLOWED_IMAGE_MIME.includes(realMime as (typeof ALLOWED_IMAGE_MIME)[number])) {
      throw new BadRequestError(`the uploaded object's type "${realMime}" is not allowed`, {
        code: ErrorCode.UNSUPPORTED_FILE_TYPE,
      });
    }

    const row = await this.organizations.findProfileRow(org.type, organizationId);
    const currentKeys = row?.gallery_keys ?? [];
    if (currentKeys.length >= MAX_GALLERY_IMAGES) {
      throw new BadRequestError(
        `the gallery already has the maximum of ${MAX_GALLERY_IMAGES} photos`,
        {
          code: ErrorCode.GALLERY_LIMIT_EXCEEDED,
        },
      );
    }
    const galleryKeys = [...currentKeys, input.storageKey];

    await this.db.transaction(async (tx) => {
      await this.organizations.updateProfileFields(org.type, organizationId, { galleryKeys }, tx);
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_GALLERY_UPDATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: organizationId,
          actorUserId: actor.actorUserId,
          metadata: { organizationId, sizeBytes: head.size, photoCount: galleryKeys.length },
          context: actor.context,
        },
        tx,
      );
    });

    const withDetails = await this.organizations.findByIdWithDetails(organizationId);
    if (!withDetails) throw new InternalError('organization vanished after gallery update');
    return this.attachMedia(withDetails);
  }

  /** Removes one gallery photo by storage key. */
  async removeGalleryImage(
    organizationId: string,
    actor: OrgActor,
    storageKey: string,
  ): Promise<OrganizationWithDetails> {
    const org = await this.getById(organizationId);
    OrganizationPolicy.assertHasProfileFields(org.type);

    const row = await this.organizations.findProfileRow(org.type, organizationId);
    const currentKeys = row?.gallery_keys ?? [];
    const galleryKeys = currentKeys.filter((k) => k !== storageKey);
    if (galleryKeys.length === currentKeys.length) {
      throw new NotFoundError('Gallery photo not found');
    }

    await this.db.transaction(async (tx) => {
      await this.organizations.updateProfileFields(org.type, organizationId, { galleryKeys }, tx);
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_GALLERY_UPDATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: organizationId,
          actorUserId: actor.actorUserId,
          metadata: { organizationId, photoCount: galleryKeys.length },
          context: actor.context,
        },
        tx,
      );
    });

    try {
      await this.storage.delete(storageKey);
    } catch (err) {
      this.log.error(
        { err, organizationId },
        'failed to delete removed gallery photo — needs a sweep',
      );
    }

    const withDetails = await this.organizations.findByIdWithDetails(organizationId);
    if (!withDetails) throw new InternalError('organization vanished after gallery update');
    return this.attachMedia(withDetails);
  }

  // --- license documents (CLINIC / VETERINARY_OFFICE only — "صور الترخيص") ---
  // Same presigned direct-to-storage shape as the gallery, own storage prefix
  // and own array column (never exposed on the public discover DTO — reviewed
  // by an admin before approval, mirrors the veterinarian application's
  // private `LICENSE_OR_ID` document at the organization level).

  private assertLicensable(type: OrganizationType): void {
    if (!LICENSABLE_TYPES.has(type)) {
      throw new BadRequestError(`${type} organizations do not have license documents`, {
        code: ErrorCode.ORGANIZATION_TYPE_NOT_SUPPORTED,
      });
    }
  }

  async requestLicenseDocumentUploadUrl(
    organizationId: string,
    input: { filename: string; mimeType: string; size: number },
  ): Promise<{
    storageKey: string;
    uploadUrl: string;
    method: 'PUT';
    headers: Record<string, string>;
    expiresInSeconds: number;
  }> {
    const org = await this.getById(organizationId);
    this.assertLicensable(org.type);

    if (!Number.isInteger(input.size) || input.size <= 0) {
      throw new BadRequestError('size must be a positive integer number of bytes');
    }
    if (input.size > MAX_IMAGE_BYTES) {
      throw new BadRequestError(`document exceeds the ${MAX_IMAGE_BYTES}-byte limit`, {
        code: ErrorCode.FILE_TOO_LARGE,
      });
    }
    if (!ALLOWED_IMAGE_MIME.includes(input.mimeType as (typeof ALLOWED_IMAGE_MIME)[number])) {
      throw new BadRequestError(`MIME type "${input.mimeType}" is not allowed for a document`, {
        code: ErrorCode.UNSUPPORTED_FILE_TYPE,
      });
    }

    const row = await this.organizations.findProfileRow(org.type, organizationId);
    if ((row?.license_document_keys?.length ?? 0) >= MAX_LICENSE_DOCUMENTS) {
      throw new BadRequestError(
        `the maximum of ${MAX_LICENSE_DOCUMENTS} license documents is already reached`,
        { code: ErrorCode.LICENSE_DOCUMENT_LIMIT_EXCEEDED },
      );
    }

    const storageKey = buildObjectKey(StoragePrefix.organizationLicenseDocuments, input.filename);
    const uploadUrl = await this.storage.getSignedUrl(storageKey, {
      operation: 'put',
      expiresIn: IMAGE_UPLOAD_URL_TTL_SECONDS,
      contentType: input.mimeType,
    });

    return {
      storageKey,
      uploadUrl,
      method: 'PUT',
      headers: { 'Content-Type': input.mimeType },
      expiresInSeconds: IMAGE_UPLOAD_URL_TTL_SECONDS,
    };
  }

  /** Registers an uploaded license document — appends to the existing array. */
  async addLicenseDocument(
    organizationId: string,
    actor: OrgActor,
    input: { storageKey: string; mimeType: string },
  ): Promise<OrganizationWithDetails> {
    const org = await this.getById(organizationId);
    this.assertLicensable(org.type);
    if (!input.storageKey.startsWith(`${StoragePrefix.organizationLicenseDocuments}/`)) {
      throw new ConflictError('storage key does not belong to organization license uploads', {
        code: ErrorCode.STORAGE_KEY_MISMATCH,
      });
    }

    const head = await this.storage.head(input.storageKey);
    if (!head) {
      throw new BadRequestError('no uploaded object exists at that storage key', {
        code: ErrorCode.STORAGE_OBJECT_MISSING,
      });
    }
    const realMime = head.contentType ?? input.mimeType;
    if (head.size > MAX_IMAGE_BYTES) {
      throw new BadRequestError('the uploaded object exceeds the size limit', {
        code: ErrorCode.FILE_TOO_LARGE,
      });
    }
    if (!ALLOWED_IMAGE_MIME.includes(realMime as (typeof ALLOWED_IMAGE_MIME)[number])) {
      throw new BadRequestError(`the uploaded object's type "${realMime}" is not allowed`, {
        code: ErrorCode.UNSUPPORTED_FILE_TYPE,
      });
    }

    const row = await this.organizations.findProfileRow(org.type, organizationId);
    const currentKeys = row?.license_document_keys ?? [];
    if (currentKeys.length >= MAX_LICENSE_DOCUMENTS) {
      throw new BadRequestError(
        `the maximum of ${MAX_LICENSE_DOCUMENTS} license documents is already reached`,
        { code: ErrorCode.LICENSE_DOCUMENT_LIMIT_EXCEEDED },
      );
    }
    const licenseDocumentKeys = [...currentKeys, input.storageKey];

    await this.db.transaction(async (tx) => {
      await this.organizations.updateProfileFields(org.type, organizationId, { licenseDocumentKeys }, tx);
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_LICENSE_DOCUMENTS_UPDATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: organizationId,
          actorUserId: actor.actorUserId,
          metadata: { organizationId, sizeBytes: head.size, documentCount: licenseDocumentKeys.length },
          context: actor.context,
        },
        tx,
      );
    });

    const withDetails = await this.organizations.findByIdWithDetails(organizationId);
    if (!withDetails) throw new InternalError('organization vanished after license document update');
    return this.attachMedia(withDetails);
  }

  /** Removes one license document by storage key. */
  async removeLicenseDocument(
    organizationId: string,
    actor: OrgActor,
    storageKey: string,
  ): Promise<OrganizationWithDetails> {
    const org = await this.getById(organizationId);
    this.assertLicensable(org.type);

    const row = await this.organizations.findProfileRow(org.type, organizationId);
    const currentKeys = row?.license_document_keys ?? [];
    const licenseDocumentKeys = currentKeys.filter((k) => k !== storageKey);
    if (licenseDocumentKeys.length === currentKeys.length) {
      throw new NotFoundError('License document not found');
    }

    await this.db.transaction(async (tx) => {
      await this.organizations.updateProfileFields(org.type, organizationId, { licenseDocumentKeys }, tx);
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_LICENSE_DOCUMENTS_UPDATED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: organizationId,
          actorUserId: actor.actorUserId,
          metadata: { organizationId, documentCount: licenseDocumentKeys.length },
          context: actor.context,
        },
        tx,
      );
    });

    try {
      await this.storage.delete(storageKey);
    } catch (err) {
      this.log.error(
        { err, organizationId },
        'failed to delete removed license document — needs a sweep',
      );
    }

    const withDetails = await this.organizations.findByIdWithDetails(organizationId);
    if (!withDetails) throw new InternalError('organization vanished after license document update');
    return this.attachMedia(withDetails);
  }

  /**
   * Organizations the user is an ACTIVE member of, with their org role in each.
   * FARM rows also carry `farmSpecies` (`POULTRY` | `SHEEP` | `CATTLE` | `MIXED`
   * | `null`) so the species-specific farm landings can filter without an extra
   * request per farm. Always `null` for non-FARM types. VETERINARY_OFFICE /
   * CLINIC rows also carry the derived subscription status plus
   * address/phone/logoUrl/galleryUrls (Veterinary Office Dashboard's "my
   * organizations" card — spec §3/§4, `OwnedOrganizationCard`) — always
   * `null`/`[]` for other types, sourced from the SAME batched `*_details`
   * query as the subscription dates (no extra round trip). `galleryUrls` lets
   * the card fall back to a registration photo when the owner hasn't set a
   * logo yet (registration collects gallery/license photos, never a logo).
   */
  async listMine(userId: string): Promise<
    Array<
      Organization & {
        myRole: string;
        farmSpecies: string | null;
        subscriptionStatus: FarmSubscriptionStatus | null;
        subscriptionEndDate: string | null;
        address: string | null;
        phone: string | null;
        logoUrl: string | null;
        galleryUrls: string[];
      }
    >
  > {
    const memberships = await this.memberships.listActiveOrganizationsForUser(userId);
    if (memberships.length === 0) return [];
    const roleByOrg = new Map(memberships.map((m) => [m.organizationId, m.roleKey]));
    const orgs = await this.organizations.findManyByIds([...roleByOrg.keys()]);

    const farmIds = orgs.filter((o) => o.type === 'FARM').map((o) => o.id);
    const speciesByOrg = new Map<string, string | null>();
    if (farmIds.length > 0) {
      const rows = (await this.db('farm_details')
        .whereIn('organization_id', farmIds)
        .select('organization_id', 'farm_species')) as Array<{
        organization_id: string;
        farm_species: string | null;
      }>;
      for (const r of rows) speciesByOrg.set(r.organization_id, r.farm_species);
    }

    const subscriptionByOrg = new Map<
      string,
      { status: FarmSubscriptionStatus; endDate: string | null }
    >();
    const profileByOrg = new Map<
      string,
      { address: string | null; phone: string | null; logoKey: string | null; galleryKeys: string[] }
    >();
    const officeIds = orgs.filter((o) => o.type === 'VETERINARY_OFFICE').map((o) => o.id);
    const clinicIds = orgs.filter((o) => o.type === 'CLINIC').map((o) => o.id);
    for (const [table, ids] of [
      ['veterinary_office_details', officeIds],
      ['clinic_details', clinicIds],
    ] as const) {
      if (ids.length === 0) continue;
      const rows = (await this.db(table)
        .whereIn('organization_id', ids)
        .select(
          'organization_id',
          'subscription_start_date',
          'subscription_end_date',
          'address',
          'phone',
          'logo_key',
          'gallery_keys',
        )) as Array<{
        organization_id: string;
        subscription_start_date: string | Date | null;
        subscription_end_date: string | Date | null;
        address: string | null;
        phone: string | null;
        logo_key: string | null;
        gallery_keys: string[] | null;
      }>;
      for (const r of rows) {
        const startDate = toDateOnlyString(r.subscription_start_date);
        const endDate = toDateOnlyString(r.subscription_end_date);
        subscriptionByOrg.set(r.organization_id, {
          status: computeFarmSubscriptionStatus(startDate, endDate),
          endDate,
        });
        profileByOrg.set(r.organization_id, {
          address: r.address,
          phone: r.phone,
          logoKey: r.logo_key,
          galleryKeys: r.gallery_keys ?? [],
        });
      }
    }
    const logoUrlByKey = new Map<string, string | null>();
    const allKeys = new Set<string>();
    for (const p of profileByOrg.values()) {
      if (p.logoKey) allKeys.add(p.logoKey);
      for (const key of p.galleryKeys) allKeys.add(key);
    }
    await Promise.all(
      [...allKeys].map(async (key) => {
        if (!logoUrlByKey.has(key)) logoUrlByKey.set(key, await this.resolveLogoUrl(key));
      }),
    );

    return orgs.map((o) => {
      const profile = profileByOrg.get(o.id);
      return {
        ...o,
        myRole: roleByOrg.get(o.id) ?? 'STAFF',
        farmSpecies: o.type === 'FARM' ? (speciesByOrg.get(o.id) ?? null) : null,
        subscriptionStatus: subscriptionByOrg.get(o.id)?.status ?? null,
        subscriptionEndDate: subscriptionByOrg.get(o.id)?.endDate ?? null,
        address: profile?.address ?? null,
        phone: profile?.phone ?? null,
        logoUrl: profile?.logoKey ? (logoUrlByKey.get(profile.logoKey) ?? null) : null,
        galleryUrls: (profile?.galleryKeys ?? [])
          .map((key) => logoUrlByKey.get(key))
          .filter((url): url is string => url != null),
      };
    });
  }

  async approve(id: string, actor: OrgActor): Promise<Organization> {
    const org = await this.getById(id);
    if (org.status !== 'PENDING') {
      throw new ConflictError('Only a pending organization can be approved');
    }
    const updated = await this.db.transaction(async (tx) => {
      const u = await this.organizations.updateStatus(
        id,
        { status: 'ACTIVE', decidedBy: actor.actorUserId, decisionReason: null },
        tx,
      );
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_APPROVED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: id,
          actorUserId: actor.actorUserId,
          metadata: { type: org.type },
          context: actor.context,
        },
        tx,
      );
      return u;
    });
    this.events.publish('organization.approved', {
      organizationId: id,
      ownerUserId: org.ownerUserId,
    });
    return updated;
  }

  async reject(id: string, reason: string, actor: OrgActor): Promise<Organization> {
    const org = await this.getById(id);
    if (org.status !== 'PENDING') {
      throw new ConflictError('Only a pending organization can be rejected');
    }
    const updated = await this.db.transaction(async (tx) => {
      const u = await this.organizations.updateStatus(
        id,
        { status: 'REJECTED', decidedBy: actor.actorUserId, decisionReason: reason },
        tx,
      );
      await this.audit.record(
        {
          action: AuditAction.ORGANIZATION_REJECTED,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: id,
          actorUserId: actor.actorUserId,
          metadata: { type: org.type, reason },
          context: actor.context,
        },
        tx,
      );
      return u;
    });
    this.events.publish('organization.rejected', {
      organizationId: id,
      ownerUserId: org.ownerUserId,
    });
    return updated;
  }

  async changeStatus(
    id: string,
    op: 'suspend' | 'activate' | 'deactivate',
    actor: OrgActor,
    reason?: string,
  ): Promise<Organization> {
    const org = await this.getById(id);
    if (org.status === 'PENDING' || org.status === 'REJECTED') {
      throw new ConflictError(
        'Use approve/reject for a pending organization; status changes apply to reviewed organizations only',
      );
    }
    const rule = NON_ADMIN_STATUS_CHANGE[op];
    if (!rule.from.includes(org.status)) {
      throw new ConflictError(`Cannot ${op} an organization in status ${org.status}`);
    }

    const updated = await this.db.transaction(async (tx) => {
      const u = await this.organizations.updateStatus(id, { status: rule.to }, tx);
      await this.audit.record(
        {
          action: rule.action,
          entityType: AuditEntityType.ORGANIZATION,
          entityId: id,
          actorUserId: actor.actorUserId,
          metadata: { from: org.status, to: rule.to, reason: reason ?? null },
          context: actor.context,
        },
        tx,
      );
      return u;
    });
    this.events.publish(rule.event, { organizationId: id, ownerUserId: org.ownerUserId });
    return updated;
  }
}
